"""empty message

Revision ID: 04b3de75f320
Revises: 
Create Date: 2023-05-17 15:29:59.181361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04b3de75f320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('typology')
    op.add_column('valla', sa.Column('format_id', sa.Integer(), nullable=True))
    op.drop_constraint('valla_typology_id_fkey', 'valla', type_='foreignkey')
    op.create_foreign_key(None, 'valla', 'format', ['format_id'], ['id'])
    op.drop_column('valla', 'typology_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('typology_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.create_foreign_key('valla_typology_id_fkey', 'valla', 'typology', ['typology_id'], ['id'])
    op.drop_column('valla', 'format_id')
    op.create_table('typology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('size', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('area', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='typology_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='typology_pkey')
    )
    op.drop_table('format')
    # ### end Alembic commands ###
