"""empty message

Revision ID: 1fdb51c04b48
Revises: da48a728cb6b
Create Date: 2023-06-12 23:49:34.274213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdb51c04b48'
down_revision = 'da48a728cb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'created_by')
    # ### end Alembic commands ###
