"""empty message

Revision ID: 20d6b1af9836
Revises: 563d58970994
Create Date: 2022-10-25 03:59:16.453586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d6b1af9836'
down_revision = '563d58970994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('picture_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'picture_url')
    # ### end Alembic commands ###
