"""empty message

Revision ID: 266aa2e5c9da
Revises: 6bab53dd67c7
Create Date: 2022-10-01 01:21:40.187925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266aa2e5c9da'
down_revision = '6bab53dd67c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('typology', sa.String(length=20), nullable=True))
    op.alter_column('valla', 'layout',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('valla', 'size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('valla', 'view',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('valla', 'route',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('valla', 'tipology')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('tipology', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('valla', 'route',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('valla', 'view',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('valla', 'size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('valla', 'layout',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('valla', 'typology')
    # ### end Alembic commands ###
