"""empty message

Revision ID: 30827a0e8396
Revises: f25b3b720af1
Create Date: 2023-06-13 16:05:51.411567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30827a0e8396'
down_revision = 'f25b3b720af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'modified_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('modified_on', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
