"""empty message

Revision ID: 31a8fb6f2d76
Revises: 741eccbb92a1
Create Date: 2023-03-15 16:21:12.184774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a8fb6f2d76'
down_revision = '741eccbb92a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('base_price', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('net_price', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('commision', sa.Integer(), nullable=True))
    op.drop_column('order', 'order_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('order', 'commision')
    op.drop_column('order', 'net_price')
    op.drop_column('order', 'discount')
    op.drop_column('order', 'base_price')
    # ### end Alembic commands ###
