"""empty message

Revision ID: 33400c845c98
Revises: b84e6ecac872
Create Date: 2023-05-16 16:14:32.435124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33400c845c98'
down_revision = 'b84e6ecac872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'typology',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('valla', 'size',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'size',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('valla', 'typology',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
