"""empty message

Revision ID: 3556b2218e39
Revises: ae14c390c6a0
Create Date: 2023-05-22 23:10:54.369454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3556b2218e39'
down_revision = 'ae14c390c6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('phone1', sa.String(length=30), nullable=False))
    op.add_column('client', sa.Column('phone2', sa.String(length=30), nullable=False))
    op.add_column('client', sa.Column('address', sa.String(length=50), nullable=False))
    op.alter_column('client', 'company',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('client', 'email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('phone', table_name='client')
    op.create_unique_constraint(None, 'client', ['phone1'])
    op.create_unique_constraint(None, 'client', ['phone2'])
    op.create_unique_constraint(None, 'client', ['address'])
    op.drop_column('client', 'phone')
    op.add_column('owner', sa.Column('phone1', sa.String(length=30), nullable=False))
    op.add_column('owner', sa.Column('phone2', sa.String(length=30), nullable=False))
    op.add_column('owner', sa.Column('address', sa.String(length=150), nullable=False))
    op.alter_column('owner', 'company',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('owner', 'email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('phone', table_name='owner')
    op.create_unique_constraint(None, 'owner', ['address'])
    op.create_unique_constraint(None, 'owner', ['phone2'])
    op.create_unique_constraint(None, 'owner', ['phone1'])
    op.drop_column('owner', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('phone', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'owner', type_='unique')
    op.drop_constraint(None, 'owner', type_='unique')
    op.drop_constraint(None, 'owner', type_='unique')
    op.create_index('phone', 'owner', ['phone'], unique=False)
    op.alter_column('owner', 'email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('owner', 'company',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_column('owner', 'address')
    op.drop_column('owner', 'phone2')
    op.drop_column('owner', 'phone1')
    op.add_column('client', sa.Column('phone', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.create_index('phone', 'client', ['phone'], unique=False)
    op.alter_column('client', 'email',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('client', 'company',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
    op.drop_column('client', 'address')
    op.drop_column('client', 'phone2')
    op.drop_column('client', 'phone1')
    # ### end Alembic commands ###
