"""empty message

Revision ID: 3bc2cea00c78
Revises: 573eb92bd18c
Create Date: 2023-06-12 00:28:56.959175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc2cea00c78'
down_revision = '573eb92bd18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valla_ibfk_2', 'valla', type_='foreignkey')
    op.create_foreign_key(None, 'valla', 'format', ['format_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.create_foreign_key('valla_ibfk_2', 'valla', 'format', ['format_id'], ['id'])
    # ### end Alembic commands ###
