"""empty message

Revision ID: 4022c86231e4
Revises: 1fdb51c04b48
Create Date: 2023-06-12 23:54:10.337889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4022c86231e4'
down_revision = '1fdb51c04b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('created_by', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'created_by')
    # ### end Alembic commands ###
