"""empty message

Revision ID: 472bde204ca7
Revises: f3b10e924403
Create Date: 2022-11-19 04:22:17.021541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472bde204ca7'
down_revision = 'f3b10e924403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('typology')
    # ### end Alembic commands ###
