"""empty message

Revision ID: 500dd5e479ba
Revises: 472bde204ca7
Create Date: 2022-12-01 16:30:10.489166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '500dd5e479ba'
down_revision = '472bde204ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_column('valla', 'lgn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('lgn', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('valla', 'lng')
    # ### end Alembic commands ###
