"""empty message

Revision ID: 69466997597d
Revises: daa350e8784d
Create Date: 2023-03-07 23:27:49.196568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69466997597d'
down_revision = 'daa350e8784d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.alter_column('client', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('order', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.alter_column('order', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('owner', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.alter_column('owner', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('typology', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.drop_column('typology', 'modified_on')
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'role')
    op.add_column('valla', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.alter_column('valla', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('valla', 'created_on')
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'created_on')
    op.add_column('typology', sa.Column('modified_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('typology', 'created_on')
    op.alter_column('owner', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('owner', 'created_on')
    op.alter_column('order', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('order', 'created_on')
    op.alter_column('client', 'modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('client', 'created_on')
    op.drop_table('role')
    # ### end Alembic commands ###
