"""empty message

Revision ID: 6a4cdf557a26
Revises: 30827a0e8396
Create Date: 2023-06-13 16:51:15.677269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a4cdf557a26'
down_revision = '30827a0e8396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_constraint('client_ibfk_1', 'client', type_='foreignkey')
    op.drop_column('client', 'user_id')
    op.alter_column('format', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_constraint('format_ibfk_1', 'format', type_='foreignkey')
    op.drop_column('format', 'user_id')
    op.alter_column('order', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('owner', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_constraint('owner_ibfk_1', 'owner', type_='foreignkey')
    op.drop_column('owner', 'user_id')
    op.alter_column('payment', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('role', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('user', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('valla', 'created_by',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('user', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('role', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('payment', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.add_column('owner', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('owner_ibfk_1', 'owner', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('owner', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('order', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.add_column('format', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('format_ibfk_1', 'format', 'user', ['user_id'], ['id'])
    op.alter_column('format', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.add_column('client', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_ibfk_1', 'client', 'user', ['user_id'], ['id'])
    op.alter_column('client', 'created_by',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
