"""empty message

Revision ID: 6bab53dd67c7
Revises: b4e854c6a024
Create Date: 2022-10-01 01:18:09.220030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bab53dd67c7'
down_revision = 'b4e854c6a024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('typology', sa.String(length=20), nullable=False))
    op.drop_column('valla', 'tipology')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('tipology', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('valla', 'typology')
    # ### end Alembic commands ###
