"""empty message

Revision ID: 78e0707394f9
Revises: b0aeb14312d9
Create Date: 2023-05-23 22:20:01.313592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78e0707394f9'
down_revision = 'b0aeb14312d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('contact_name', sa.String(length=150), nullable=False))
    op.add_column('client', sa.Column('company_id', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'client', ['company_id'])
    op.drop_column('client', 'name')
    op.add_column('owner', sa.Column('document_id', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'owner', ['document_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner', type_='unique')
    op.drop_column('owner', 'document_id')
    op.add_column('client', sa.Column('name', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_column('client', 'company_id')
    op.drop_column('client', 'contact_name')
    # ### end Alembic commands ###
