"""empty message

Revision ID: 790407a9aa19
Revises: 500dd5e479ba
Create Date: 2023-03-04 16:36:37.300472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790407a9aa19'
down_revision = '500dd5e479ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('province', sa.String(length=100), nullable=False))
    op.add_column('valla', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'address')
    op.drop_column('valla', 'province')
    # ### end Alembic commands ###
