"""empty message

Revision ID: 99f61c1d628c
Revises: ad6e97016d98
Create Date: 2023-05-17 18:02:30.645600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f61c1d628c'
down_revision = 'ad6e97016d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('format', 'shape')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('format', sa.Column('shape', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
