"""empty message

Revision ID: ad6e97016d98
Revises: 4aeb39a7ee7f
Create Date: 2023-05-17 17:46:42.843301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6e97016d98'
down_revision = '4aeb39a7ee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('shape', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'shape')
    # ### end Alembic commands ###
