"""empty message

Revision ID: b0986c4907a5
Revises: 79c1e62a5d39
Create Date: 2023-05-24 04:10:07.102431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0986c4907a5'
down_revision = '79c1e62a5d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owner', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('owner', 'contact',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('owner', 'phone1',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('owner', 'phone2',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('owner', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('owner', 'address',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('owner', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owner', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('owner', 'address',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('owner', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('owner', 'phone2',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('owner', 'phone1',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('owner', 'contact',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('owner', 'name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
