"""empty message

Revision ID: b0aeb14312d9
Revises: e52b5d39a953
Create Date: 2023-05-23 21:45:25.117380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0aeb14312d9'
down_revision = 'e52b5d39a953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('comment', sa.String(length=250), nullable=True))
    op.add_column('format', sa.Column('comment', sa.String(length=250), nullable=True))
    op.add_column('order', sa.Column('comment', sa.String(length=250), nullable=True))
    op.add_column('owner', sa.Column('comment', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'comment')
    op.drop_column('order', 'comment')
    op.drop_column('format', 'comment')
    op.drop_column('client', 'comment')
    # ### end Alembic commands ###
