"""empty message

Revision ID: b4e854c6a024
Revises: 
Create Date: 2022-09-27 17:23:47.306725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4e854c6a024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('modified_on', sa.DateTime(), nullable=False))
    op.add_column('client', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('client', 'created_on')
    op.add_column('order', sa.Column('modified_on', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('start_rent_on', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('end_rent_on', sa.DateTime(), nullable=True))
    op.drop_column('order', 'rent_end')
    op.drop_column('order', 'rent_start')
    op.drop_column('order', 'created')
    op.add_column('owner', sa.Column('modified_on', sa.DateTime(), nullable=False))
    op.drop_column('owner', 'created_on')
    op.add_column('payment', sa.Column('due_on', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('payment_on', sa.DateTime(), nullable=True))
    op.drop_column('payment', 'payment_date')
    op.drop_column('payment', 'due_date')
    op.add_column('user', sa.Column('modified_on', sa.DateTime(), nullable=False))
    op.drop_column('user', 'created_on')
    op.add_column('valla', sa.Column('size', sa.String(length=20), nullable=False))
    op.add_column('valla', sa.Column('modified_on', sa.DateTime(), nullable=False))
    op.alter_column('valla', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('valla', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('valla', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('valla', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('valla', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('valla', 'modified_on')
    op.drop_column('valla', 'size')
    op.add_column('user', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user', 'modified_on')
    op.add_column('payment', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('payment', 'payment_on')
    op.drop_column('payment', 'due_on')
    op.add_column('owner', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('owner', 'modified_on')
    op.add_column('order', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('rent_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('rent_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'end_rent_on')
    op.drop_column('order', 'start_rent_on')
    op.drop_column('order', 'modified_on')
    op.add_column('client', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('client', 'is_active')
    op.drop_column('client', 'modified_on')
    # ### end Alembic commands ###
