"""empty message

Revision ID: da48a728cb6b
Revises: 3bc2cea00c78
Create Date: 2023-06-12 17:28:29.591841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da48a728cb6b'
down_revision = '3bc2cea00c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('valla_ibfk_4', 'valla', type_='foreignkey')
    op.drop_constraint('valla_ibfk_5', 'valla', type_='foreignkey')
    op.drop_constraint('valla_ibfk_1', 'valla', type_='foreignkey')
    op.drop_constraint('valla_ibfk_3', 'valla', type_='foreignkey')
    op.create_foreign_key(None, 'valla', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'valla', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'valla', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'valla', 'owner', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.create_foreign_key('valla_ibfk_3', 'valla', 'order', ['order_id'], ['id'])
    op.create_foreign_key('valla_ibfk_1', 'valla', 'client', ['client_id'], ['id'])
    op.create_foreign_key('valla_ibfk_5', 'valla', 'user', ['user_id'], ['id'])
    op.create_foreign_key('valla_ibfk_4', 'valla', 'owner', ['owner_id'], ['id'])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###
