"""empty message

Revision ID: e52b5d39a953
Revises: 3556b2218e39
Create Date: 2023-05-23 15:28:20.210261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e52b5d39a953'
down_revision = '3556b2218e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('picture_url', sa.String(length=400), nullable=True))
    op.add_column('format', sa.Column('picture_url', sa.String(length=400), nullable=True))
    op.add_column('order', sa.Column('picture_url', sa.String(length=400), nullable=True))
    op.add_column('owner', sa.Column('picture_url', sa.String(length=400), nullable=True))
    op.add_column('user', sa.Column('picture_url', sa.String(length=400), nullable=True))
    op.alter_column('valla', 'picture_url',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'picture_url',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    op.drop_column('user', 'picture_url')
    op.drop_column('owner', 'picture_url')
    op.drop_column('order', 'picture_url')
    op.drop_column('format', 'picture_url')
    op.drop_column('client', 'picture_url')
    # ### end Alembic commands ###
