"""empty message

Revision ID: e9fb59a10c85
Revises: cd579b31040f
Create Date: 2023-04-27 22:29:54.765782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fb59a10c85'
down_revision = 'cd579b31040f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('price_canvas', sa.Float(), nullable=True))
    op.add_column('valla', sa.Column('traffic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'traffic')
    op.drop_column('valla', 'price_canvas')
    # ### end Alembic commands ###
