"""empty message

Revision ID: f1acfaf41bcc
Revises: b0986c4907a5
Create Date: 2023-06-11 23:56:06.486610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1acfaf41bcc'
down_revision = 'b0986c4907a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('owner_ibfk_1', 'owner', type_='foreignkey')
    op.create_foreign_key(None, 'owner', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner', type_='foreignkey')
    op.create_foreign_key('owner_ibfk_1', 'owner', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
