"""empty message

Revision ID: f25b3b720af1
Revises: 4022c86231e4
Create Date: 2023-06-13 15:59:41.352971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f25b3b720af1'
down_revision = '4022c86231e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_column('client', 'modified_on')
    op.add_column('format', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('format', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('format', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('order', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('order', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('order', 'modified_on')
    op.add_column('owner', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('owner', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_column('user', 'modified_on')
    op.add_column('valla', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.alter_column('valla', 'created_by',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('valla_ibfk_8', 'valla', type_='foreignkey')
    op.drop_column('valla', 'user_id')
    op.drop_column('valla', 'modified_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('modified_on', mysql.DATETIME(), nullable=True))
    op.add_column('valla', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('valla_ibfk_8', 'valla', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('valla', 'created_by',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_column('valla', 'updated_on')
    op.add_column('user', sa.Column('modified_on', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'updated_on')
    op.drop_column('role', 'created_by')
    op.drop_column('role', 'updated_on')
    op.drop_column('role', 'created_on')
    op.drop_column('payment', 'created_by')
    op.drop_column('payment', 'updated_on')
    op.drop_column('payment', 'created_on')
    op.drop_column('owner', 'created_by')
    op.drop_column('owner', 'updated_on')
    op.add_column('order', sa.Column('modified_on', mysql.DATETIME(), nullable=True))
    op.alter_column('order', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('order', 'created_by')
    op.drop_column('order', 'updated_on')
    op.alter_column('format', 'created_on',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('format', 'created_by')
    op.drop_column('format', 'updated_on')
    op.add_column('client', sa.Column('modified_on', mysql.DATETIME(), nullable=True))
    op.drop_column('client', 'created_by')
    op.drop_column('client', 'updated_on')
    # ### end Alembic commands ###
