"""empty message

Revision ID: f3b10e924403
Revises: e50760a75ab6
Create Date: 2022-11-01 21:51:00.022004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b10e924403'
down_revision = 'e50760a75ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('valla', sa.Column('lgn', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valla', 'lgn')
    op.drop_column('valla', 'lat')
    # ### end Alembic commands ###
