"""empty message

Revision ID: fc7cae2d99d7
Revises: c68786e549ce
Create Date: 2022-10-03 20:06:05.266088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7cae2d99d7'
down_revision = 'c68786e549ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('valla', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('valla', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('valla', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valla', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('valla', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('valla', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('valla', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
