"""empty message

Revision ID: 4aeb39a7ee7f
Revises: 9b5cca956b19
Create Date: 2023-05-17 17:30:20.630842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeb39a7ee7f'
down_revision = '9b5cca956b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('format', sa.Column('shape', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('format', 'shape')
    # ### end Alembic commands ###
