"""empty message

Revision ID: 9b5cca956b19
Revises: 04b3de75f320
Create Date: 2023-05-17 15:32:22.400200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5cca956b19'
down_revision = '04b3de75f320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('valla', sa.Column('format_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'valla', 'format', ['format_id'], ['id'])
    op.drop_column('valla', 'typology_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valla', sa.Column('typology_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'valla', type_='foreignkey')
    op.drop_column('valla', 'format_id')
    op.drop_table('format')
    # ### end Alembic commands ###
